---
deployment:
  tasks:
    # - export DEPLOYPATH=/home/connexxtel/public_html/
    # export DEPLOYPATH=/home/cidsan/members.cidsan.org/
    - export DEPLOYPATH=/home/cidsan/backoffice.cidsan.org/
    - /bin/cp -R * $DEPLOYPATH
